
# POST https://powertrainafttest.azurewebsites.net/Account/Register HTTP/1.1
# content-type: application/json

# {
#   "email":"ddimarzio@powertrain.com",
#   "username":"ddimarzio",
#   "password":"test2"
# }

# POST https://powertrainafttest.azurewebsites.net/Account/Login HTTP/1.1
# content-type: application/json

# {
#   "username":"dondimarzio",
#   "password":"test"
# }

# POST http://powertrainafttest.azurewebsites.net/Account/GetData HTTP/1.1
# content-type: application/json

# {
#   "SessionID" : "82986c8c-3b98-4e5a-afa0-9166058e9cd2",
#   "UserID" : "46"
# }

  # "UserID": 46,
  # "SessionID": "82986c8c-3b98-4e5a-afa0-9166058e9cd2",
  # "Username": "Don",
  # "Rank": "TestRank",
  # "Role": "User",
  # "Notes": [],
  # "Bookmarks": [],
  # "userLoggedIn": true

# POST http://powertrainafttest.azurewebsites.net/Flashcard/GetStack HTTP/1.1
# content-type: application/json

# {
#   "SessionID" : "1118721c-15df-475a-815c-799ddbcba264",
#   "amount" : "29",
#   "chapters" : "0"
# }

POST http://powertrainafttest.azurewebsites.net/Account/RequestPassword HTTP/1.1
content-type: application/json

{
  "email" : "ddimarzio@powertrain.com"
}

